name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'   # Garder Java 11

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarCloud Scanner 4.6
        run: |
          curl -sSLo sonarscanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonarscanner.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /opt
          echo "/opt/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

      - name: Verify Java Version for SonarScanner
        run: java -version

      - name: Verify SonarScanner installation
        run: sonar-scanner --version

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.GITHUBACTIONSTOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=AbdellaouiHajar1_ProjetChatbot \
            -Dsonar.organization=abdellaouihajar1 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
